const express=require("express"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const app=express(),PORT=process.env.PORT||3000,DATA=path.join(__dirname,"data","posts.json");
app.disable("x-powered-by");app.use(express.json({limit:"8mb"}));app.use(express.static(path.join(__dirname,"public"),{etag:true,maxAge:"1h"}));
const clean=(v,n=5000)=>String(v??"").trim().slice(0,n);
function read(){return JSON.parse(fs.readFileSync(DATA,"utf8"))} function write(x){fs.writeFileSync(DATA,JSON.stringify(x,null,2))}
function validate(b){const p={title:clean(b.title,140),excerpt:clean(b.excerpt,320),content:clean(b.content,12000),category:clean(b.category,60),author:clean(b.author,80),image:clean(b.image,5500000)},errors={};
if(p.title.length<5)errors.title="Title must be at least 5 characters.";if(p.excerpt.length<20)errors.excerpt="Excerpt must be at least 20 characters.";if(p.content.length<50)errors.content="Content must be at least 50 characters.";if(!p.category)errors.category="Category is required.";if(!p.author)errors.author="Author is required.";if(p.image&&!p.image.startsWith("data:image/"))errors.image="Invalid image data.";return{p,errors}}
app.get("/api/posts",(req,res)=>{try{let a=read(),q=clean(req.query.q,100).toLowerCase(),c=clean(req.query.category,60).toLowerCase();if(q)a=a.filter(p=>[p.title,p.excerpt,p.content,p.author,p.category].join(" ").toLowerCase().includes(q));if(c&&c!=="all")a=a.filter(p=>p.category.toLowerCase()===c);a.sort((x,y)=>new Date(y.createdAt)-new Date(x.createdAt));res.json(a)}catch{res.status(500).json({message:"Unable to load articles."})}});
app.get("/api/posts/:id",(req,res)=>{try{const p=read().find(x=>x.id===req.params.id);p?res.json(p):res.status(404).json({message:"Article not found."})}catch{res.status(500).json({message:"Unable to load article."})}});
app.post("/api/posts",(req,res)=>{try{const v=validate(req.body);if(Object.keys(v.errors).length)return res.status(400).json({message:"Validation failed.",errors:v.errors});const a=read(),now=new Date().toISOString(),p={id:crypto.randomUUID(),...v.p,createdAt:now,updatedAt:now};a.push(p);write(a);res.status(201).json(p)}catch{res.status(500).json({message:"Unable to create article."})}});
app.put("/api/posts/:id",(req,res)=>{try{const v=validate(req.body);if(Object.keys(v.errors).length)return res.status(400).json({message:"Validation failed.",errors:v.errors});const a=read(),i=a.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({message:"Article not found."});a[i]={...a[i],...v.p,updatedAt:new Date().toISOString()};write(a);res.json(a[i])}catch{res.status(500).json({message:"Unable to update article."})}});
app.delete("/api/posts/:id",(req,res)=>{try{const a=read(),n=a.filter(x=>x.id!==req.params.id);if(n.length===a.length)return res.status(404).json({message:"Article not found."});write(n);res.json({message:"Article deleted successfully."})}catch{res.status(500).json({message:"Unable to delete article."})}});
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
app.listen(PORT,()=>console.log(`BlogSpace Task 2 running at http://localhost:${PORT}`));